{{- with .Values.secret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.secretStore }}
  target:
    name: {{ .secretName }}
  dataFrom:
    - extract:
        key: {{ .remoteKey }}
{{- end }}
